### ISSUE TITLE
Migrate hpa from autoscaling/v1 to autoscaling/v2beta2

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/sumologic-kubernetes-collection#1069]
`autoscaling/v2beta1` has been deprecated in k8s `1.19` in favor of `autoscaling/v2beta2` which was introduced in `1.12` so this should be safe to change since we're "only" supporting kubernetes `1.14` and up.

This will allow hpa to autoscale based not only on cpu but also on memory usage.

**EDIT**

Actually it seems we're using `autoscaling/v1`

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/bea1ba167d48ae46449c22224bd7e61020aa348f/deploy/helm/sumologic/templates/metrics-hpa.yaml#L2

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/bea1ba167d48ae46449c22224bd7e61020aa348f/deploy/helm/sumologic/templates/hpa.yaml#L2

**Comment by pmalek-sumo** [comment]
As per https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics

> Notice that the targetCPUUtilizationPercentage field has been replaced with an array called metrics. The CPU utilization metric is a resource metric, since it is represented as a percentage of a resource specified on pod containers. Notice that you can specify other resource metrics besides CPU. By default, the only other supported resource metric is memory. 

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

Hence marking this as breaking change
