### ISSUE TITLE
Add to comments-indentation rule to yamllint ruleset on CI

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/sumologic-kubernetes-collection#1178]
Add [comments-indentation](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments_indentation) rule to `yamllint` ruleset on CI

**Comment by pmalek-sumo** [comment]
We'd have to decide if we actually want this since it would require a couple of changes to our yaml files:

* comments about commented code ( starting with `##` ) would need to be uncommented and default would have to be used or a different approach would need to be used:

  ```yaml
  sumologic:
    setup:
      ## uncomment to force collection installation (disables k8s version verification)
      # force: true
    job:
      stuff: x
  ```
  
  ```
    3:5       error    comment not indented like content  (comments-indentation)
  ```
  
  So in order to fix it we'd have to do the following:
  
  ```yaml
  sumologic:
    setup:
      ## uncomment to force collection installation (disables k8s version verification)
      force: false
    job:
      stuff: x
  ```

* similarly 

  ```yaml
  kube-prometheus-stack:
  
    # global:
      ## Reference to one or more secrets to be used when pulling images
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ##
      # imagePullSecrets:
      #   - name: "image-pull-secret"
  ```

  would have to become
  
  ```yaml
    global:
      ## Reference to one or more secrets to be used when pulling images
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ##
      imagePullSecrets: []
      # - name: "image-pull-secret"
  ```
