### ISSUE TITLE
Disable node-exporter and kube-state-metrics 

### ISSUE THREAD

**Issue by Barry-Shippit** [SumoLogic/sumologic-kubernetes-collection#1239]
**Is your feature request related to a problem? Please describe.**
We currently mange our own node-exporters and kube-state-metrics , along with prometheus and other custom metrics. Deploying this solution means we're doubling up on components that aren't required, and consuming addition resources.

**Describe the solution you'd like**
When deploying, ideally there should be an option to disable/enable node-exporter/kube-state-metris/etc.
An other approach we'd like is to be able disable/enable prometheus all together, and have our single prometheus remote write to the fluentd services.

**Describe alternatives you've considered**
* [sumologic-prometheus-scraper](https://github.com/SumoLogic/sumologic-prometheus-scraper), however it doesn't support custom headers.
* Replace our existing setup with this collection:
  * No option to configure grafana (dashboards as code, install plugins)
  * No option to customise alert manager or alerts
  * No support for highly available prometheus
  * Difficult to update to newer versions of components
  * Difficult to customise what metics get sent to sumo logic (found this collection inundates sumo logic with unrequired metrics)

**Additional context**
Part of our custom setup of prometheus and additional components is managed with [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)

**Comment by sumo-drosiek** [comment]
Hi @Barry-Shippit,

to disable `node-exporter` and `kube-state-metrics` you can add this while upgrade/install our collection:
```
kube-prometheus-stack:
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
```

Did you consider to set up our collection in [with existing prometheus operator](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/existingPrometheusDoc.md) scenario? Seems like this can be a solution for that issue

**Comment by pmalek-sumo** [comment]
Hi @Barry-Shippit 

Based on `kube-prometheus-stack` @ `12.3.0` helm chart, you can disable prometheus':
* node-exporter by setting `kube-prometheus-stack.nodeExporter.enabled` to `false` [ref](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.3.0/charts/kube-prometheus-stack/values.yaml#L1166-L1169)
* kube-state-metrics by setting `kube-prometheus-stack. kubeStateMetrics.enabled` to `false` [ref](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.3.0/charts/kube-prometheus-stack/values.yaml#L1131-L1134)

As for configuring our collection with your own Prometheus please refer to our docs: [How to install if you have standalone Prometheus
](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/standAlonePrometheus.md)

If you'd like to use Prometheus from our collection together with your own Prometheus the refer to: [How to install our Prometheus side by side with your existing Prometheus](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/standAlonePrometheus.md)

All other helm chart configuration options from `kube-prometheus-stack` can be set the same way as the above mentioned `nodeExporter` and `kubeStateMetrics`.

Let us know if that makes sense.

**Comment by perk-sumo** [comment]
Hi @Barry-Shippit, I'm closing this now. Please let us know if you need anything else.

**Comment by obenziane2** [comment]
I have disabled it too and still trying to install the node-exporter 

```
  kubeStateMetrics:
    enabled: false
    serviceMonitor:
      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      interval:
  nodeExporter:
    enabled: false
    serviceMonitor:
      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      interval:
```

**Comment by perk-sumo** [comment]
Ok, I'm reopening this.
> An other approach we'd like is to be able disable/enable prometheus all together

That is totally achievable, we have a documentation on [already using existing Prometheus Operator](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/existingPrometheusDoc.md)

> have our single prometheus remote write to the fluentd services.

By default we have a multiple Remote Write sections.
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/values.yaml#L1453
That's because sending all the metrics to one endpoint can easily exhaust the endpoint quota.

**Comment by pmalek-sumo** [comment]
@obenziane2 Do you mind checking it once again?

I've checked now and setting (as you've outlined it)

```yaml
kube-prometheus-stack:
  kubeStateMetrics:
    enabled: false
    serviceMonitor:
      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      interval:
  nodeExporter:
    enabled: false
    serviceMonitor:
      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      interval:
```

does work for me (i.e. node exporter and kube state metrics do not install). Can you check if the parent key (in your custom setup which you've mentioned in the description) is properly set to propagate the values? We use `kube-prometheus-stack` (which is the default) for all the keys related to [prometheus chart](https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-12.3.0/charts/kube-prometheus-stack).
