### ISSUE TITLE
Silently dropped logs with out of box config

### ISSUE THREAD

**Issue by laupow** [SumoLogic/sumologic-kubernetes-collection#1255]
**Describe the bug**
Higher volume log environments need better configuration guardrails to ensure logs aren't dropped silently.

Recently 2 different engineers have expected logs and found none in our production environment.

One instance was a long running service that had intermittent message missing (screenshot attached) Another instance was a new Deployment that did not get logs captured (logs were verified with `kubectl logs <pod>`. Screenshot in [ticket](https://support.sumologic.com/hc/requests/57674))

<img width="2343" alt="MissingLogsInSumo" src="https://user-images.githubusercontent.com/6674176/102551873-d8f9a700-4085-11eb-8c48-86694cb67b58.png">

**Logs**
Logs available in [ticket](https://support.sumologic.com/hc/requests/57674) 

**Command used to install/upgrade Collection**
```
helm upgrade -i -f sumologic-collector/base-eks-values.yaml \
  -f sumologic-collector/${ENVIRONMENT}-values.yaml \
  --namespace $NAMESPACE \
  --kube-context ${KUBECTL_CONTEXT} \
  $RELEASE_NAME \
  --version v1.3.1 \
  --set sumologic.accessKey=$SUMOLOGIC_ACCESS_KEY \
  sumologic/sumologic 
```
with Helm 2

**Configuration**
```
fluentd:
  logs:
    autoscaling:
      enabled: true
    containers:
      sourceCategory: '%{pod_name}'
      sourceCategoryPrefix: production/
      sourceCategoryReplaceDash: '-'
      sourceName: '%{namespace}.%{pod}.%{container}'
    default:
      sourceCategoryPrefix: production/
    kubelet:
      sourceCategoryPrefix: production/
    statefulset:
      nodeSelector:
        company.com/nodegroup-name: general-public
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: general-public
    systemd:
      sourceCategoryPrefix: production/
  persistence:
    enabled: true
prometheus-operator:
  enabled: false
sumologic:
  accessId: <removed>
  accessKey: <removed>
  clusterName: us-east-1-eks-production
  metrics:
    enabled: false
```

**To Reproduce**
I have not been able to reproduce the issue. On Dec 15 we manually changed the HPA minimum from 3 to 7 nobody has reported issues since then, but 🤷 

The issue occurs in our production environment so there is somewhat of a disincentive to reproduce it :)

**Expected behavior**
Provide a clear signal (pod crash, log message) when there is a capacity issue or other case that might cause logs to drop. 

**Environment (please complete the following information):**
 - **Collection version** (e.g. `helm ls -n sumologic`):  1.3.1
 - **Kubernetes version** (e.g. `kubectl version`): 1.15.11
 - **Cloud provider**: AWS
 - **Others**:

**Anything else do we need to know**
*  I noticed 1.3.4 includes a memory related fix, which we don't have running yet. I have observed a few `fluentd` pod restarts, but they haven't correlated with times when logs are missing.
* The HPA out of the box in our environment is _very_ spiky. I have to imagine this much pod churn is not a good configuration.

### fluend pod metrics, HPA minimum adjusted Dec 15
<img width="1073" alt="FluendPodMetrics7days" src="https://user-images.githubusercontent.com/6674176/102550953-5d4b2a80-4084-11eb-9f68-d6c70874820d.png">

### Sumo collector volume
<img width="276" alt="Screen Shot 2020-12-17 at 3 41 06 PM" src="https://user-images.githubusercontent.com/6674176/102550728-eb72e100-4083-11eb-8e53-93e6b841b9df.png">
