### ISSUE TITLE
Migration script creates wrong selector for ServiceMonitors.

### ISSUE THREAD

**Issue by kkujawa-sumo** [SumoLogic/sumologic-kubernetes-collection#1258]
**Describe the bug**
[upgrade-2.0.0.sh](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/upgrade-2.0.0.sh) creates wrong selector for ServiceMonitors.

**Logs**
```
Error: UPGRADE FAILED: cannot patch "monitoring-sumologic-fluentd-events" with kind StatefulSet: StatefulSet.apps "monitoring-sumologic-fluentd-events" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && cannot patch "monitoring-sumologic-fluentd-metrics" with kind StatefulSet: StatefulSet.apps "monitoring-sumologic-fluentd-metrics" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && cannot patch "collection-sumologic-fluentd-logs" with kind ServiceMonitor: ServiceMonitor.monitoring.coreos.com "collection-sumologic-fluentd-logs" is invalid: spec.selector.matchLabels.sumologic.com/scrape: Invalid value: "boolean": spec.selector.matchLabels.sumologic.com/scrape in body must be of type string: "boolean"
...
```

**To Reproduce**
Step described in [migration guide](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/v2_migration_doc.md)

**Expected behavior**

Migration script should create selector in following way
```
        selector:
          matchLabels:
            sumologic.com/app: fluentd-logs
            sumologic.com/scrape: "true"
```
instead of
```
        selector:
          matchLabels:
            sumologic.com/app: fluentd-logs
            sumologic.com/scrape: true
```
