### ISSUE TITLE
Add security best practices doc

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/sumologic-kubernetes-collection#1470]
Let's add a security doc documenting most common security configuration options that users might want to tweak e.g. configuring fluentd's `securityContext` with `readOnlyRootFilesystem: true` which requires adding `tmp` as a separate volume (to prevent it being read only as well)

```yaml
fluentd:
  ...
  logs:
    ...
    extraVolumeMounts:
      - mountPath: /tmp/
        name: tmp-volume
    extraVolumes:
      - emptyDir: {}
        name: tmp-volume
```
