### ISSUE TITLE
Helm warning: cannot overwrite table with non table for tolerations (map[])

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#1534]
**Environment:**
 - **Collection**: v2.0.5
 - **Helm**: 3.5.2

When overriding `tolerations` property for Fluentd or OTC, Helm throws warnings about `tolerations` being a map instead of a list.

These warning are due to `tolerations` properties being defined as an empty map `{}` instead of an empty list `[]` in the chart's `values.yaml` file.

Here's an example `values.tolerations.yaml` file:

```yaml
fluentd:
  events:
    statefulset:
      tolerations:
      - key: "example-key"
        operator: "Exists"
        effect: "NoSchedule"

  logs:
    statefulset:
      tolerations:
      - key: "example-key"
        operator: "Exists"
        effect: "NoSchedule"

  metrics:
    statefulset:
      tolerations:
      - key: "example-key"
        operator: "Exists"
        effect: "NoSchedule"

otelagent:
  daemonset:
    tolerations:
    - key: "example-key"
      operator: "Exists"
      effect: "NoSchedule"

otelcol:
  deployment:
    tolerations:
    - key: "example-key"
      operator: "Exists"
      effect: "NoSchedule"

sumologic:
  accessId: dummy
  accessKey: dummy
```

And the result of calling `helm template` with it:

```console
$ helm template collection sumologic/sumologic --values values.tolerations.yaml > /dev/null
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
coalesce.go:200: warning: cannot overwrite table with non table for tolerations (map[])
```
