### ISSUE TITLE
Add support for arm64 architecture

### ISSUE THREAD

**Issue by ophelan** [SumoLogic/sumologic-kubernetes-collection#1565]
We currently operate a large number of k8s clusters in our organization. We'd like to begin to leveraging arm64 architecture in some cases.

Currently the sumologic-kubernetes-collection appears to support only amd64, though I suspect the underlying components (i.e. fluent-bit) are all arm64 capable. Ideally all components would have support, but at a minimum the fluent-bit agent should, permitting it's deployment as a DaemonSet on mixed-architecture clusters, while other services could have a nodeSelector configured for `kubernetes.io/arch` to prevent those workloads from landing on arm64 nodes.

**Comment by astencel-sumo** [comment]
Hi @ophelan, you should be able to use Fluent Bit on arm64 nodes today with Sumo Logic collection by using the upstream images from [fluent/fluent-bit](https://hub.docker.com/r/fluent/fluent-bit/), which are multi-platform. Add this to your `values.yaml` file:

```yaml
fluent-bit:
    image:
        repository: fluent/fluent-bit
```

I hope to have to more to share about ARM support in the near future.

**Comment by aquam8** [comment]
This is what I have had to do:
- run fluent-bit from upstream docker hub repo: fluent/fluent-bit
- add nodeAffinity for fluentd to run in amd64 nodes

It isn't possible to run the upstream release of fluentd - sumo's release is required and does not run on ARM currently. It would be awesome if it could so we would not have to run mixed arch cluster.

**Comment by astencel-sumo** [comment]
Thanks for checking fluent-bit on ARM @aquam8, this is good news.

As for Fluentd on ARM, there's actually an open [PR](https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/187) which, when merged, will make all future Fluentd images in Sumo Logic Kubernetes Collection multi-platform, so no changes will be necessary on the Fluentd side.

There is currently one multiplatform image pushed to our [ECR repository](https://gallery.ecr.aws/sumologic/kubernetes-fluentd): `1.12.2-sumo-1-alpha.1`, you can use it like this:

```yaml
fluentd:
  image:
    tag: 1.12.2-sumo-1-alpha.1
```

**Comment by aquam8** [comment]
Oh great to know! Thank you!!

**Comment by astencel-sumo** [comment]
Hello everyone interested in running Sumo k8s collection on ARM, here are the latest updates:
- Fluentd images for ARM are now available - check out https://gallery.ecr.aws/sumologic/kubernetes-fluentd, images from `1.12.2-sumo-1` up are multi-arch with `linux/amd64`, `linux/arm/v7` and `linux/arm64` architectures.
- Setup job images for ARM are now available - check out https://gallery.ecr.aws/sumologic/kubernetes-setup, images from `3.1.0` up are multi-arch with `linux/amd64`, `linux/arm/v7` and `linux/arm64` architectures.

Below is the configuration that has worked for me on ARM64 with the latest `v2.1.1` release of the collection chart:

values.yaml:
```yaml
fluentd:
  image:
    tag: 1.12.2-sumo-1
kube-prometheus-stack:
  kube-state-metrics:
    image:
      repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics
      tag: v1.9.8
  prometheus:
    prometheusSpec:
      thanos: null
sumologic:
  accessId: xxx
  accessKey: xxx
  setup:
    job:
      image:
        tag: 3.1.1
```

Install command:

```shell
helm install collection sumologic/sumologic --values values.yaml
```
