### ISSUE TITLE
systemd sourceCategory `kuberntes/system` does not appear to be configurable

### ISSUE THREAD

**Issue by ophelan** [SumoLogic/sumologic-kubernetes-collection#1623]
We're making changes to our sourceName and sourceCategory parameters to bring defaults in line with what our log management team prefers. To that effect, we've set the following parameters in `values.yaml`, which appear to be every available option according to the documentation:

```
fluentd:
  kubelet:
    sourceName: k8s_kubelet
    sourceCategory: app_testenv
  containers:
    sourceName: "%{namespace}/%{pod_name}"
    sourceCategory: app_testenv
  systemd:
    sourceCategory: app_testenv
  events:
    sourceCategory: app_testenv
```

Despite this, we're still seeing events with a sourceCategory of `kubernetes/system` originating from `dockerd` and `containerd`. My expectation was that the `systemd` configuration block would override this. So, I believe either I'm missing something, or this parameter isn't always taking effect.

**Comment by sumo-drosiek** [comment]
@ophelan Tanks for question

Which version of k8s collection do you use?
Probably you should put configuration under `fluentd.logs` instead of `logs`:

```
fluentd:
  logs:
    kubelet:
      sourceName: k8s_kubelet
      sourceCategory: app_testenv
    containers:
      sourceName: "%{namespace}/%{pod_name}"
      sourceCategory: app_testenv
    systemd:
      sourceCategory: app_testenv
  events:
    sourceCategory: app_testenv
```
