### ISSUE TITLE
Possiblity to add custom annotations in serviceAccount

### ISSUE THREAD

**Issue by vmayerupgrade** [SumoLogic/sumologic-kubernetes-collection#1644]
**Is your feature request related to a problem? Please describe.**
No not a problem

**Describe the solution you'd like**
I would like to have a condition in the Fluentd Service account in the Helm chart

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sumologic.metadata.name.roles.serviceaccount" . }}
  # TO add something like that
  {{- if .Values.sumologic.serviceaccount.annotation.common}}
  annotations:
    {{- include "sumologic.serviceaccount.common" . | nindent 4 }}
  {{- end }}
  # END
  labels:
    app: {{ template "sumologic.labels.app.roles.serviceaccount" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
{{- if .Values.sumologic.pullSecrets }}
imagePullSecrets:
{{ toYaml .Values.sumologic.pullSecrets | indent 2 }}
{{- end }}
```

**Describe alternatives you've considered**
Modifying the chart myself which is not the best way for maintenance.

**Additional context**
The reason I would like it is to be able to add an annotation for the fluent S3 bucket https://docs.fluentd.org/output/s3 with Web identity which needs the AMI role ARN to be added in the annotations of the service account.
