### ISSUE TITLE
No logs sent to Sumo with `collectionMonitoring` set to `false`

### ISSUE THREAD

**Issue by andrzej-stencel** [SumoLogic/sumologic-kubernetes-collection#1849]
Collection version: v2.1.6

When I set `sumologic.collectionMonitoring` to `false` in my `values.yaml`, I expect to only logs from collection components (Fluentd, Fluent Bit, Prometheus etc.) to be excluded, but I can see no logs at all being sent to Sumo. If I set `sumologic.collectionMonitoring` to `true`, I can see logs all right.

# Steps to reproduce:

1. Create `values.yaml` file with `sumologic.collectionMonitoring: false` like this:

    ```yaml
    sumologic:
      accessId: ***
      accessKey: ***
      collectionMonitoring: false
    ```

1. Install collection in a Kubernetes cluster with Helm like:

    ```shell
    $ helm install sumologic sumologic/sumologic --version 2.1.6 --values values.yaml
    ```

# Actual result:

1. No logs in Sumo

# Expected result:

1. Logs available in Sumo

# Workaround

To work around this issue, remove the `sumologic.collectionMonitoring` value (or explicitly set it to the default value `true`) and set the `fluentd.logs.containers.excludeNamespaceRegex` value to the namespace that collection is running in.

For example, if you installed collection in `monitoring` namespace (with `helm install -n monitoring ...`, add the following to your `values.yaml`:

```yaml
fluentd:
  logs:
    containers:
      excludeNamespaceRegex: "monitoring"
sumologic:
  collectionMonitoring: true
```

# Other information

The cause of this issue is [this line](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v2.1.6/deploy/helm/sumologic/conf/logs/logs.source.containers.conf#L67) that generates a Fluentd configuration like:

```
  <filter containers.**>
    @type kubernetes_sumologic
    @include logs.kubernetes.sumologic.filter.conf
    exclude_namespace_regex "monitoring|"
  </filter>
```

The `"monitoring|"` regex seems to match everything, which causes logs from all namespaces to be excluded.
