### ISSUE TITLE
Possible data duplication

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#1859]
**Describe the bug**
If across one fluentd chunk there is multiple message groups:
https://github.com/SumoLogic/fluentd-output-sumologic/blob/1b38827347e03a60d080b1edd2b9905f80b85982/lib/fluent/plugin/out_sumologic.rb#L353-L358

and sending one of the message group fails, all of the groups are going to be send again. 

**Logs**
N/A

**Command used to install/upgrade Collection**
```
sumo-make upgrade
kubectla apply -f secret.yaml
kubectla apply -f logs-generator.yaml
```

**To Reproduce**

take receiver mock from: https://github.com/SumoLogic/sumologic-kubernetes-tools/pull/158
and run it: `cargo run -- --drop-rate 60 --print-logs | tee out_1.txt`

Run collection in vagrant with given `values.local.yaml`
```
sumologic:
  setupEnabled: false
fluentd:
  logs:
    statefulset:
      replicaCount: 3
    containers:
      extraOutputPluginConf: |
        <filter **>
          @type record_modifier
          <record>
            _sumo_metadata ${record["_sumo_metadata"][:fields] = "#{record["_sumo_metadata"][:fields]},random=#{rand(1..10)}"; record["_sumo_metadata"]}
          </record>
        </filter>
  events:
    enabled: false
  metrics:
    enabled: false

fluent-bit:

  config:
    inputs: |
      [INPUT]
          Name                tail
          Path                /var/log/containers/*.log
          Parser              containerd
          Tag                 containers.*
          Refresh_Interval    1
          Rotate_Wait         60
          Mem_Buf_Limit       512MB
          Skip_Long_Lines     On
          DB                  /tail-db/tail-containers-state-sumo.db
          DB.Sync             Normal

falco:
  enabled: false
```

apply the following secret:
```
apiVersion: v1
data:
  endpoint-control_plane_metrics_source: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-events: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-logs: aHR0cDovLzE5Mi4xNjguNzguMTozMDAwL3JlY2VpdmVy
  endpoint-metrics: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-metrics-apiserver: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-metrics-kube-controller-manager: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-metrics-kube-scheduler: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-metrics-kube-state: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-metrics-kubelet: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
  endpoint-metrics-node-exporter: aHR0cDovL3JlY2VpdmVyLW1vY2sucmVjZWl2ZXItbW9jazozMDAwL3JlY2VpdmVy
kind: Secret
metadata:
  name: sumologic
  namespace: sumologic
type: Opaque

```

apply the following logs-generator configuration
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: logs-generator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-generator
  namespace: logs-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logs-generator
  template:
    metadata:
      labels:
        name: logs-generator
    spec:
      containers:
      - image: sumologic/kubernetes-tools:dev-latest
        imagePullPolicy: IfNotPresent
        name: logs-generator
        command:
          - logs-generator
          - --time-resolution=1 
          - --random-patterns=1
```

Wait some time, and run following command

```
cat out_1.txt | grep -oP '"log".*' | sort | uniq -c | sort | grep -v 'pps' | grep -v Total | grep -v overlimit | sort | tail -n 200
```

**Expected behavior**
no duplicates

**Environment (please complete the following information):**
 - **Collection version** (e.g. `helm ls -n sumologic`):
 - **Kubernetes version** (e.g. `kubectl version`):
 - **Cloud provider**:
 - **Others**:

**Anything else do we need to know**
Add any other context about the problem here, e.g. issue happens only occasionally.
