### ISSUE TITLE
Audit logs are getting piled up on the host or worker node while running the fluentd agent as a Statefulset

### ISSUE THREAD

**Issue by ujala-singh** [SumoLogic/sumologic-kubernetes-collection#2247]
![Screenshot 2022-04-26 at 2 54 53 PM](https://user-images.githubusercontent.com/59909223/165268519-94f33c4a-f9ff-4c36-ae8e-fa1b94203a4f.png)
**Describe the bug**
I am running the fluentd agent as a statefulset on a set of nodes. These sts pods are producing the audit logs in a large number which are getting pushed to the default path ```/var/log/audit.log``` on the host or node itself. If I am trying to pass the the ENV Variable ```AUDIT_LOG_PATH: /fluentd/sumologic-audit.log```, it's not working at all. Somehow logs are still getting pushed to the same location on the host. After some days the host disk space is getting pilled up and eventually we have to remove the logs manually. This is more like misconfiguration than bug and as the result of the issue, the documentation should be updated.

Looks like environment variable ```AUDIT_LOG_PATH``` doesn't have any effect. The audit logs are not going to the location mentioned in the environment variable. Somehow it is going to /var/log/audit.log in the Host system. 

1. Even though INFO logging in enabled, I can see fluented generating huge amount of logs in the audit log. How can I make fluentd to write very small amount of audit log?
2. Why is the audit log is going to /var/log/audit.log  even when  I gave different log path using environment variable 'AUDIT_LOG_PATH'

**Logs**
```
type=PATH msg=audit(1650960991.423:53007893): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f15791eaa52b7497ba8f5e229a.log" inode=1441808 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.423:53007894): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.423:53007894): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f15791eaa52b7497ba8f5e229a.log.meta" inode=1441809 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.455:53007895): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.455:53007895): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f1aeb433dabba926008a4f7801.log" inode=1441810 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.455:53007896): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.455:53007896): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f1aeb433dabba926008a4f7801.log.meta" inode=1441811 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.459:53007904): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.459:53007904): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f1b2a323cf6d3fcb97adbe6823.log" inode=1441812 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.459:53007905): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.459:53007905): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f1b2a323cf6d3fcb97adbe6823.log.meta" inode=1441813 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.491:53007909): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.491:53007909): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f1b8c6c5d1ccbeb580a3c40128.log" inode=1441824 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.491:53007910): item=0 name="/fluentd/buffer/logs.trace/" inode=1441793 dev=103:0e mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.491:53007910): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f1b8c6c5d1ccbeb580a3c40128.log.meta" inode=1441825 dev=103:0e mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.503:53007912): item=0 name="/fluentd/buffer/logs.trace/" inode=1048577 dev=103:05 mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.503:53007912): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f212cd6fc8684258260e8ae663.log" inode=1048600 dev=103:05 mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.503:53007913): item=0 name="/fluentd/buffer/logs.trace/" inode=1048577 dev=103:05 mode=042775 ouid=999 ogid=999 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1650960991.503:53007913): item=1 name="/fluentd/buffer/logs.trace/buffer.q5dd8a4f212cd6fc8684258260e8ae663.log.meta" inode=1048601 dev=103:05 mode=0100644 ouid=999 ogid=999 rdev=00:00 nametype=DELETE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
```

**Configuration**
Configuration used for Collection e.g. values.yaml for helm.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sumologic-sumologic-fluentd-logs
  labels:
    app: sumologic-sumologic-fluentd-logs
    chart: "sumologic-2.7.0"
    release: "sumologic"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: sumologic-sumologic-fluentd-logs
  serviceName: sumologic-sumologic-fluentd-logs-headless
  podManagementPolicy: "Parallel"
  template:
    metadata:
      annotations:
        checksum/config: ebc5a88862ef489c861e455d990302ac2f661195054d71206676003855a229e9
      labels:
        app: sumologic-sumologic-fluentd-logs
        chart: "sumologic-2.7.0"
        release: "sumologic"
        heritage: "Helm"
    spec:
      serviceAccountName: sumologic-sumologic
      nodeSelector:
        node-role.kubernetes.io/worker-fluentd-sumologic: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sumologic-sumologic-fluentd-logs
                  - sumologic-sumologic-fluentd-metrics
                - key: app
                  operator: In
                  values:
                  - prometheus-operator-prometheus
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: config-volume
        configMap:
          name: sumologic-sumologic-fluentd-logs
      securityContext:
        fsGroup: 999
      priorityClassName: "high-priority"
      containers:
      - name: fluentd
        image: public.ecr.aws/sumologic/kubernetes-fluentd:1.14.6-sumo-2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 3000Mi
          requests:
            cpu: 600m
            memory: 1500Mi
        ports:
        - name: fluent-bit
          containerPort: 24321
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/
        - name: buffer
          mountPath: "/fluentd/buffer"
        env:
        - name: SUMO_ENDPOINT_DEFAULT_LOGS_SOURCE
          valueFrom:
            secretKeyRef:
              name: sumologic
              key: endpoint-logs
        - name: ADDITIONAL_PLUGINS
          value: ""
        - name: AUDIT_LOG_PATH
          value: /fluentd/sumologic-audit.log
  volumeClaimTemplates:
  - metadata:
      name: buffer
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: sumologic-fluentd
      resources:
        requests:
          storage: 30Gi
```
