### ISSUE TITLE
support additional methods of providing credentials in helm chart installation

### ISSUE THREAD

**Issue by mars64** [SumoLogic/sumologic-kubernetes-collection#2308]
**Is your feature request related to a problem? Please describe.**

tldr; as far as I can tell the only way to install this chart is by providing credentials in-line with a `helm` install, which precludes secrets handling solutions like [secrets-store-csi-driver](https://secrets-store-csi-driver.sigs.k8s.io/). As we currently rely on the secrets-store-csi-driver to handle secrets for our GitOps deployments, we effectively cannot deploy this chart.

My findings:

As a newbie to SumoLogic and this chart, I tried to implement this chart in a GitOps fashion (ArgoCD) by leveraging our current [secrets-store-csi-driver](https://secrets-store-csi-driver.sigs.k8s.io/)+[secrets-store-csi-driver-provider-aws](https://github.com/aws/secrets-store-csi-driver-provider-aws) configuration instead of manually providing credentials on a CLI. 

The Secrets-Store-CSI combo exposes secrets from off-cluster (e.g. `SecretsManager`) and provisions Kubernetes `secrets` as `volumes` when a workload with permission requests it. A podspec mounts the `volume`, then uses something like a `secretKeyRef` to get the value of the secret.

I was able to hack around some bits of the credentials handling by creating the `secretProviderClass` and supplying values to this chart such as:

```
fluentd:
  logs:
    extraEnvVars:
      - name: SUMOLOGIC_ACCESSID
        valueFrom:
          secretKeyRef:
            name: sumologic-secrets
            key: sumologicKeyId
      - name: SUMOLOGIC_ACCESSKEY
        valueFrom:
          secretKeyRef:
            name: sumologic-secrets
            key: sumologicAccessKey
    extraVolumes:
      - name: sumologic-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sumologic-secrets"
    extraVolumeMounts:
      - name: sumologic-secrets
        mountPath: "/mnt/secrets-store"
        readOnly: true
```

This mostly seemed to work, except I suddenly realized there's a [bunch of terraform](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/deploy/helm/sumologic/conf/setup) that has to run to create a [hardcoded secret name](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/_helpers.tpl#L820). That secret never gets created because [the shell script that runs the terraform to create it ](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/conf/setup/setup.sh) is run by [a job that cannot be configured to obtain secrets in this way](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/setup/job.yaml).

**Describe the solution you'd like**

I would like to be able to use this chart in a way that allows me to provide secrets in more flexible ways -- in this case, by using a volume mount + `secretKeyRef`. 

Ideally, I'd only have to define the method of obtaining the secret once, and all components will know how to use it.

**Describe alternatives you've considered**

I tried hacking around passing the credentials in-line by explicitly configuring volumes and volumeMounts in the `fluentd` configurations, to no avail.

It seems possible that a quick solution would be to configure [this job](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/setup/job.yaml#L51) to use the same volume/volumeMount/secretKeyref configurations as defined in the [component configuration](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/e0169fb8d4285a03d108bc5e674f9435c05e6922/deploy/helm/sumologic/values.yaml) (`fluentd` in this case).

**Additional context**

I am _only_ configuring logs in this case. I have disabled all other telemetry collection, which is why I focus on the `.Values.fluentd` path in this ticket.
