### ISSUE TITLE
Fluentd events and logs statefulset pods cannot be scraped by prometheus when running on an istio service mesh

### ISSUE THREAD

**Issue by linxcat** [SumoLogic/sumologic-kubernetes-collection#2395]
Related to Sumologic support ticket [#73209](https://support.sumologic.com/hc/requests/73209)

In a sumologic-kubernetes-collection deployment of any version (2.0-2.8), a prometheus server pod correctly configured to otherwise correctly scrape direct https connections (not via a service following mTLS) via the mounting of certificates and the use of the tlsConfig.caFile, certFile, and keyFile values (as well as insecureSkipVerify) cannot successfully connect to fluentd pods, even though the same configuration options do allow connection to other pieces such as fluentbit daemonset pods.

In a sumologic-kubernetes-collection deployment with the included prometheus deployment turned off (aka "existing prometheus") and volume mounted certificates included via custom values at the prometheus operator level, the following serviceMonitors are in place:
```
prometheus:
  additionalServiceMonitors:
- name: collection-sumologic-fluentd-logs
    additionalLabels:
      sumologic.com/app: fluentd-logs
    endpoints:
    - port: metrics
      scheme: "https"
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        sumologic.com/app: fluentd-logs
        sumologic.com/scrape: "true"
  - name: collection-sumologic-fluentd-events
    additionalLabels:
      sumologic.com/app: fluentd-events
    endpoints:
    - port: metrics
      scheme: "https"
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true
    namespaceSelector:
      matchNames:
        - monitoring
    selector:
      matchLabels:
        sumologic.com/app: fluentd-events
        sumologic.com/scrape: "true"
  - name: collection-fluent-bit
    additionalLabels:
      sumologic.com/app: collection-fluent-bit
    endpoints:
    - port: http
      path: /api/v1/metrics/prometheus
      scheme: "https"
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true
    namespaceSelector:
      matchNames:
        - monitoring
    selector:
      matchLabels:
        app.kubernetes.io/name: fluent-bit
        sumologic.com/scrape: "true"
```
In this configuration, fluentbit scrape succeeds over https, and the other two fail over the same with "unexpected EOF".
During debugging, removing istio from both of these statefulsets and altering the above to remove the tlsConfig parent key and with a scheme of "http" it still fails, this time with a "peer reset connection".\
Both of these are the error that I would expect when working with istio were I using the wrong protocol (the first with https to an http endpoint, and the second with http to https) but is not possible for both to be the case.
Other such configured serviceMonitors function as expected, and scraping works correctly. Among over a dozen running services, these two fluentd ones are the only two that do not work as expected.
