### ISSUE TITLE
Instruction to overwrite prometheus operator config to add remote write url is dangerous

### ISSUE THREAD

**Issue by djsly** [SumoLogic/sumologic-kubernetes-collection#257]
https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/v0.9.0/deploy/helm/prometheus-overrides.yaml

The file will disable `alertmanager` and `grafana` as well as remove any `additionalServiceMonitors` that the original installation might have created
```
alertmanager:
  enabled: false
grafana:
  enabled: false
  defaultDashboardsEnabled: false
prometheus:
  additionalServiceMonitors:
    - name: collection-sumologic
```

The user should be asked to update his prometheus-operator with a prometheus-override which only contains

```
prometheus:
  prometheusSpec:
    remoteWrite:
```

Since the Documentation is asking him

https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/master/deploy#overwrite-prometheus-remote-write-configuration

>If you have not already customized your remote write configuration, run the following to update the remote write configuration of the prometheus operator by installing with the prometheus overrides file we provide below.

**Comment by bergerx** [comment]
We also got hit by this as well, glad that it was a test cluster.

A colleague of mine just followed the docs expecting to enable the sumologic integration, which he was successful, but he ended up removing half of our stack. Our own prometheus-operator is configured with quite a bit detailed, when reviewing this integration, i was actually quite surprised not many people complaining about this issue.

So we can't really disable these stuff from our prometheus-operator, and I was trying to come up with a set of extra values yaml to enable sumologic and prevent sumologic to deploy its own operator as a dependency.

Here is what i came up with after reviewing the chart, i'm still testing this but i believe that there must be a reason why the sumologic provided installation method for clusters with an existing prometheus-operatos is not like this. I'd like to help identifying issues if possible.

**sumologic-values.yaml**
Note: `prometheus-operator` is explicitly disabled here.
```
sumologic:
  accessId: "${SUMO_ACCESS_ID}"
  accessKey: "${SUMO_ACCESS_KEY}"
  endpoint: "${SUMO_ENDPOINT}"
prometheus-operator:
  enabled: false
fluentd:
  logs:
    containers:
      excludeNamespaceRegex: "(kube-system|monitoring|sumologic|logging|infra)"
```

**prometheus-operator-sumologic-extra-values.yaml**
Note: Mind that I omit the `additionalServiceMonitors` section, due to the way our prometheus operator is configured.
```
# Ensure we use pre 1.14 recording rules consistently as current content depends on them.
kubeTargetVersionOverride: 1.13.0-0

prometheus:

  ## We don't need the define the additionalServiceMonitors for sumologic, we already have
  ## operator configured to watch for all service monitors in the cluster in any
  ## namespace.
  # additionalServiceMonitors: ...

  prometheusSpec:
    # ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec
    thanos:
      baseImage: quay.io/thanos/thanos
      version: v0.10.0

    ## Containers allows injecting additional containers. This will allow using
    ## "$(CHART)" and "$(NAMESPACE)" below in the remoteWrite rules below. This
    ## will be merged into the prometheus-config-reloader container defition via
    ## strategic merge patch.
    ## See this link for more details:
    ## https://github.com/helm/charts/blob/1e6a30c3b8fd1034a955ea7bd1d0d96df2cae9dd/stable/prometheus-operator/crds/crd-prometheus.yaml#L1083-L1093
    containers:
    - name: "prometheus-config-reloader"
      env:
      - name: CHART
        valueFrom:
          configMapKeyRef:
            name: sumologic-configmap
            key: fluentdMetrics
      - name: NAMESPACE
        valueFrom:
          configMapKeyRef:
            name: sumologic-configmap
            key: fluentdNamespace

    remoteWrite:
    - ... {cropped: all the remoteWrite rules as provided by sumologic} ...
```
