### ISSUE TITLE
Prometheus doesn't start in v3 when fluentd is used as metadata provider

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2688]
Config reloader expects `FLUENTD_METRICS_SVC` but is given the `METADATA_METRICS_CVS` instead and crashes as a result.

**Comment by astencel-sumo** [comment]
This only happens if you have references to `FLUENTD_METRICS_SVC` in your `user-values.yaml` file, which can happen if you have modified the `kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite` section.

In that case, you need to replace the occurrences of `FLUENTD_METRICS_SVC` with `METADATA_METRICS_SVC` in your `user-values.yaml`. For example, replace this:

```yaml
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local.:9888/prometheus.metrics.state
```

with this:

```yaml
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: http://$(METADATA_METRICS_SVC).$(NAMESPACE).svc.cluster.local.:9888/prometheus.metrics.state
```
