### ISSUE TITLE
values.yaml missing "resources:" section for prometheus

### ISSUE THREAD

**Issue by emcay** [SumoLogic/sumologic-kubernetes-collection#275]
There is no configuration available in the values.yaml for prometheus resource declaration such as

  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 768Mi
      cpu: 0.5

**Comment by frankreno** [comment]
Hi @emcay, this is available thru the standard Helm sub chart mechanism. In the Prometheus-Operator chart, this is done using `prometheus.prometheusSpec.resources`.  We use this chart as a dependency, so to change any of its properties, you simply need to add `prometheus-operator` prefix to tell helm which chart you want to set.  So for example, you can add the following to our Helm chart values.yaml.

```
prometheus-operator:
  prometheus:
    prometheusSpec:
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 768Mi
          cpu: 0.5
```
