### ISSUE TITLE
How to set nodeSelector on the otelcol daemonset?

### ISSUE THREAD

**Issue by poblahblahblah** [SumoLogic/sumologic-kubernetes-collection#2861]
Hello,

I can't quite grok how to get this set. We have windows clusters and it appears as though this does not (yet) work on windows so we need to ignore them.

**Comment by astencel-sumo** [comment]
You should be able to set `nodeSelector` for the otelcol daemonset like this:

```yaml
otellogs:
  daemonset:
    nodeSelector:
      kubernetes.io/os: linux
```

Please let me know if this doesn't work for you.
