### ISSUE TITLE
Logs from two different containers of one pod show up in Sumo as coming from one of the containers

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#2862]
Version: `v3.0.1`
Kubernetes: v1.25.3
Container runtime: containerd

I have a pod that has two containers in it. I'm seeing the same `_sourceName` value and `container` value for logs from both containers, but I would expect them to be different.

### Steps to reproduce

- Create a k8s cluster with e.g. `minikube start --kubernetes-version=1.25.3 --container-runtime=containerd`
- Create a pod with two containers

    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: logger
    spec:
      selector:
        matchLabels:
          app: logger
      replicas: 1
      template:
        metadata:
          # annotations:
          #   sumologic.com/singleline.sourceCategory: single-line-sc
          labels:
            app: logger
        spec:
          containers:
          - name: singleline
            image: busybox
            args: [/bin/sh, -c, 'i=0; while true; do echo "singleline-$i"; i=$((i+1)); sleep 1; done']
            resources: {}

          - name: multiline
            image: busybox
            args: [/bin/sh, -c, 'i=0; while true; do echo "2001-02-03T04:05:06 multiline 1 log $i first line"; echo "  multiline 1 log $i second line"; echo "  multiline 1 log $i third line"; i=$((i+1)); sleep 1; done']
            resources: {}
    ```

- Install collection chart with `helm install -n sumo --create-namespace col sumologic/sumologic --version=3.0.1 --values user-values.yaml` with the following values file:

    ```yaml
    sumologic:
      accessId: xxx
      accessKey: yyy

      clusterName: two-containers

      events:
        enabled: false
      logs:
        enabled: true
      metrics:
        enabled: false
      traces:
        enabled: false
    ```

### Expected output

Logs from `multiline` container should be logged with `container=multiline`, logs from `singleline` container should be logged with `container=singleline`

### Actual output

Logs from both containers are logged with `container=singleline`

![image](https://user-images.githubusercontent.com/70892616/218075162-a6957e81-5719-4271-8f14-340f9b8a2947.png)
