### ISSUE TITLE
Migration to 3.0 Script result in error. update-collection-v3: error migrating values [1:1] string was used where mapping is expected

### ISSUE THREAD

**Issue by AdamDomagalsky** [SumoLogic/sumologic-kubernetes-collection#3007]
**Describe the bug** 
update-collection-v3 result in error (see **Logs**)

Following the instructions from [Kubernetes Collection v3.0.0 - Breaking Changes #Migrating the configuration
](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/v3-migration-doc.md#migrating-the-configuration)

**Logs**
```bash
# ./update-collection-v3 -in user-values.yaml -out new-values.yaml
WARNING! Changes in metrics-server detected, which may require manual migration
For details please see the following documentations:
  - https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/v3-migration-doc.md
  - https://github.com/bitnami/charts/tree/5b09f7a7c0d9232f5752840b6c4e5cdc56d7f796/bitnami/metrics-server#to-600
WARNING! Tracing config migrated to v3, please check the output file. For more details see documentation: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/v3-migration-doc.md#tracinginstrumentation-changes
2023/04/26 12:33:35 error migrating values [1:1] string was used where mapping is expected
    >  1 | ��_helmctl:
           ^
       2 |
       3 |   chart: sumologic
       4 |`
```

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.
```yaml
_helmctl:
  chart: sumologic
fluent-bit:
  config:
    customParsers: |
      [PARSER]
          Name         containerd
          Format       regex
          Regex        ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
    inputs: |
      [INPUT]
          Name                tail
          Path                /var/log/containers/*.log
          Parser              containerd
          Tag                 containers.*
          Refresh_Interval    1
          Rotate_Wait         60
          Mem_Buf_Limit       5MB
          Skip_Long_Lines     On
          DB                  /tail-db/tail-containers-state-sumo.db
          DB.Sync             Normal
      [INPUT]
          Name            systemd
          Tag             host.*
          DB              /tail-db/systemd-state-sumo.db
          Systemd_Filter  _SYSTEMD_UNIT=addon-config.service
          Systemd_Filter  _SYSTEMD_UNIT=addon-run.service
          Systemd_Filter  _SYSTEMD_UNIT=cfn-etcd-environment.service
          Systemd_Filter  _SYSTEMD_UNIT=cfn-signal.service
          Systemd_Filter  _SYSTEMD_UNIT=clean-ca-certificates.service
          Systemd_Filter  _SYSTEMD_UNIT=containerd.service
          Systemd_Filter  _SYSTEMD_UNIT=coreos-metadata.service
          Systemd_Filter  _SYSTEMD_UNIT=coreos-setup-environment.service
          Systemd_Filter  _SYSTEMD_UNIT=coreos-tmpfiles.service
          Systemd_Filter  _SYSTEMD_UNIT=dbus.service
          Systemd_Filter  _SYSTEMD_UNIT=docker.service
          Systemd_Filter  _SYSTEMD_UNIT=efs.service
          Systemd_Filter  _SYSTEMD_UNIT=etcd-member.service
          Systemd_Filter  _SYSTEMD_UNIT=etcd.service
          Systemd_Filter  _SYSTEMD_UNIT=etcd2.service
          Systemd_Filter  _SYSTEMD_UNIT=etcd3.service
          Systemd_Filter  _SYSTEMD_UNIT=etcdadm-check.service
          Systemd_Filter  _SYSTEMD_UNIT=etcdadm-reconfigure.service
          Systemd_Filter  _SYSTEMD_UNIT=etcdadm-save.service
          Systemd_Filter  _SYSTEMD_UNIT=etcdadm-update-status.service
          Systemd_Filter  _SYSTEMD_UNIT=flanneld.service
          Systemd_Filter  _SYSTEMD_UNIT=format-etcd2-volume.service
          Systemd_Filter  _SYSTEMD_UNIT=kube-node-taint-and-uncordon.service
          Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
          Systemd_Filter  _SYSTEMD_UNIT=ldconfig.service
          Systemd_Filter  _SYSTEMD_UNIT=locksmithd.service
          Systemd_Filter  _SYSTEMD_UNIT=logrotate.service
          Systemd_Filter  _SYSTEMD_UNIT=lvm2-monitor.service
          Systemd_Filter  _SYSTEMD_UNIT=mdmon.service
          Systemd_Filter  _SYSTEMD_UNIT=nfs-idmapd.service
          Systemd_Filter  _SYSTEMD_UNIT=nfs-mountd.service
          Systemd_Filter  _SYSTEMD_UNIT=nfs-server.service
          Systemd_Filter  _SYSTEMD_UNIT=nfs-utils.service
          Systemd_Filter  _SYSTEMD_UNIT=node-problem-detector.service
          Systemd_Filter  _SYSTEMD_UNIT=ntp.service
          Systemd_Filter  _SYSTEMD_UNIT=oem-cloudinit.service
          Systemd_Filter  _SYSTEMD_UNIT=rkt-gc.service
          Systemd_Filter  _SYSTEMD_UNIT=rkt-metadata.service
          Systemd_Filter  _SYSTEMD_UNIT=rpc-idmapd.service
          Systemd_Filter  _SYSTEMD_UNIT=rpc-mountd.service
          Systemd_Filter  _SYSTEMD_UNIT=rpc-statd.service
          Systemd_Filter  _SYSTEMD_UNIT=rpcbind.service
          Systemd_Filter  _SYSTEMD_UNIT=set-aws-environment.service
          Systemd_Filter  _SYSTEMD_UNIT=system-cloudinit.service
          Systemd_Filter  _SYSTEMD_UNIT=systemd-timesyncd.service
          Systemd_Filter  _SYSTEMD_UNIT=update-ca-certificates.service
          Systemd_Filter  _SYSTEMD_UNIT=user-cloudinit.service
          Systemd_Filter  _SYSTEMD_UNIT=var-lib-etcd2.service
          Max_Entries     1000
          Read_From_Tail  true
fluentd:
  logs:
    kubelet:
      enabled: false
    podDisruptionBudget:
      minAvailable: 1
    statefulset:
      replicaCount: 2
  metrics:
    podDisruptionBudget:
      minAvailable: 1
    statefulset:
      replicaCount: 2
  persistence:
    enabled: false
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      remoteWrite:
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state
        writeRelabelConfigs:
        - action: keep
          regex: kube-state-metrics;(?:kube_statefulset_replicas|kube_deployment_spec_replicas|kube_node_info|kube_hpa_spec_max_replicas|kube_hpa_spec_min_replicas|kube_hpa_status_(condition|(current|desired)_replicas))
          sourceLabels:
          - job
          - __name__
        - action: labelmap
          regex: (pod|service)
          replacement: service_discovery_${1}
        - action: labeldrop
          regex: (pod|service|container)
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state
        writeRelabelConfigs:
        - action: keep
          regex: kube-state-metrics;(?:kube_pod_status_phase)
          sourceLabels:
          - job
          - __name__
        - action: labeldrop
          regex: container
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state
        writeRelabelConfigs:
        - action: keep
          regex: kube-state-metrics;(?:kube_pod_container_status_ready|kube_pod_container_status_terminated_reason|kube_pod_container_status_waiting_reason|kube_pod_container_status_restarts_total)
          sourceLabels:
          - job
          - __name__
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.container
        writeRelabelConfigs:
        - action: labelmap
          regex: container_name
          replacement: container
        - action: drop
          regex: POD
          sourceLabels:
          - container
        - action: keep
          regex: kubelet;.+;(?:container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_fs_usage_bytes|container_fs_limit_bytes|container_cpu_cfs_throttled_seconds_total)
          sourceLabels:
          - job
          - container
          - __name__
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.container
        writeRelabelConfigs:
        - action: keep
          regex: kubelet;(?:container_network_receive_bytes_total|container_network_transmit_bytes_total)
          sourceLabels:
          - job
          - __name__
        - action: labeldrop
          regex: container
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.node
        writeRelabelConfigs:
        - action: keep
          regex: node-exporter;(?:node_load1|node_load5|node_load15|node_cpu_seconds_total)
          sourceLabels:
          - job
          - __name__
      - remoteTimeout: 5s
        url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.operator.rule
        writeRelabelConfigs:
        - action: keep
          regex: 'instance:node_filesystem_usage:sum|instance:node_network_receive_bytes:rate:sum|cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile|node_namespace_pod:kube_pod_info:|:kube_pod_info_node_count:|node:node_num_cpu:sum|:node_cpu_utilisation:avg1m|node:node_cpu_utilisation:avg1m|node:cluster_cpu_utilisation:ratio|:node_cpu_saturation_load1:|node:node_cpu_saturation_load1:|:node_memory_utilisation:|node:node_memory_bytes_total:sum|node:node_memory_utilisation:ratio|node:cluster_memory_utilisation:ratio|:node_memory_swap_io_bytes:sum_rate|node:node_memory_utilisation:|node:node_memory_utilisation_2:|node:node_memory_swap_io_bytes:sum_rate|:node_disk_utilisation:avg_irate|node:node_disk_utilisation:avg_irate|:node_disk_saturation:avg_irate|node:node_disk_saturation:avg_irate|node:node_filesystem_usage:|node:node_filesystem_avail:|:node_net_utilisation:sum_irate|node:node_net_utilisation:sum_irate|:node_net_saturation:sum_irate|node:node_net_saturation:sum_irate|node:node_inodes_total:|node:node_inodes_free:'
          sourceLabels:
          - __name__
      - url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.A
        writeRelabelConfigs:
        - action: keep
          regex: .*-A-.*
          sourceLabels:
          - service
      - url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.B
        writeRelabelConfigs:
        - action: keep
          regex: .*-B
          sourceLabels:
          - service
      - url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.C
        writeRelabelConfigs:
        - action: keep
          regex: .*-C-.*
          sourceLabels:
          - service
      - url: http://$(FLUENTD_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.D
        writeRelabelConfigs:
        - action: keep
          regex: D
          sourceLabels:
          - service
      scrapeInterval: 2m
sumologic:
  accessId: xxxxxxxxxx
  accessKey: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
  clusterName: cluster-name
  sources:
    metrics:
      A:
        name: A
      B:
        name: B
      C:
        name: C
      D:
        name: D
```

**To Reproduce** Steps to reproduce the behavior.

`./update-collection-v3 -in user-values.yaml -out new-values.yaml` where user-values.yaml is Configuration mentioned aboce

**Expected behavior**: To return new-values.yaml

**Environment:**
- **Collection version**: sumologic-2.19.1
- **Kubernetes version**: 1.24
- **Cloud provider**: EKS
- **Others**: Windows PS / WSL ubuntu

**Anything else do we need to know**: Tried to run with and without docker.
