### ISSUE TITLE
sumologic setup job error "Object ID must be a valid hexadecimal string."

### ISSUE THREAD

**Issue by cogito-cmurphy** [SumoLogic/sumologic-kubernetes-collection#3115]
Hello,

Recently took over our sumologic implementation and have to move it forward for EKS 1.24. I have a barebones sumologic 3.4.0 deployment going but it doesn't seem to create open telemetry collectors in sumo like I would expect. 
My bare bones values

```
  values:
    kube-prometheus-stack:
        enabled: false
    metadata:
      persistence:
        storageClass: general-purpose-csi
    sumologic:
      envFromSecret: sumologic-api-token-xacct-externalsecrets
      logs:
        fields:
          - cluster
          - container
          - deployment
          - host
          - namespace
          - node
          - pod
          - service
      metrics:
        enabled: false
```

the sumologic setup job has this failure 
```
sumologic-sumologic-setup-ms66j setup 2023-06-30T12:31:55.985Z [DEBUG] provider: using plugin: version=5
sumologic-sumologic-setup-ms66j setup sumologic_monitor_folder.tf_monitor_folder_1: Creating...
sumologic-sumologic-setup-ms66j setup 2023-06-30T12:31:56.510Z [DEBUG] provider.terraform-provider-sumologic_v2.18.2: 2023/06/30 12:31:56 [DEBUG] Request: [Method=POST] [URL=https://api.us2.sumologic.com/api/v1/monitors?parentId=30NT0-6B2VY-NUOW8&] [Headers=map[Authorization:[xxxxxxxxxxx] Content-Type:[application/json] User-Agent:[SumoLogicTerraformProvider/2.18.2]]]. Response: [StatusCode=400 Bad Request]
sumologic-sumologic-setup-ms66j setup ╷
sumologic-sumologic-setup-ms66j setup │ Error: {"id":"62O2S-SSXZ4-HYEB3","errors":[{"code":"user:invalid_object_id","message":"Object ID must be a valid hexadecimal string.","meta":{"id":"30NT0-6B2VY-NUOW8"}}]}
```

**Comment by kkujawa-sumo** [comment]
I'm not able to reproduce this problem. Do you still observe this? Why have you removed `daemonset` and `statefulset` from `sumologic.logs.fields`?

**Comment by cogito-cmurphy** [comment]
> I'm not able to reproduce this problem. Do you still observe this? Why have you removed `daemonset` and `statefulset` from `sumologic.logs.fields`?

Yes im still having this issue. I have / had a ticket open for the fields issue, because we didnt have those fields in https://help.sumologic.com/docs/manage/fields/ it was blocking setup. I am now adding these fields and trying again.

**Comment by cogito-cmurphy** [comment]
For this specific error I can "bypass" it by doing the code below but it doesnt setup otel collectors
```
sumologic:
      setup:
        monitors:
          enabled: false
```
