### ISSUE TITLE
error converting YAML to JSON: yaml | Chart version 3.9.0

### ISSUE THREAD

**Issue by itsmesuniljacob** [SumoLogic/sumologic-kubernetes-collection#3151]
**Describe the bug** YAML parse error when calling sumo logic helm chart by passing the below values

```
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 65
        targetCPUUtilizationPercentage: 90
```

**Logs** `Error: YAML parse error on cp-sumo-collection/charts/sumologic/templates/logs/fluentd/hpa.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context`

**Command used to install/upgrade Collection** `helm install <chart>`

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.
```
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 65
        targetCPUUtilizationPercentage: 90
```

**To Reproduce** Steps to reproduce the behavior.
Override `..Values.fluentd.logs.autoscaling.targetCPUUtilizationPercentage`  

**Expected behavior** A clear and concise description of what you expected to happen.

Chart should rendered without issues
**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`):
- **Kubernetes version** (e.g. `kubectl version`): 26
- **Cloud provider**:
- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.
![image](https://github.com/SumoLogic/sumologic-kubernetes-collection/assets/16597269/77bdafd6-a29a-4ae5-841d-8e1c6e959ab2)

Please see line number 250. the construct `-type` is rendered wrong

This issues is only for chart version 3.9.0 and above
