### ISSUE TITLE
Helm Chart Version v3.10 Logs Collector results in hundreds of "Failed to process entry" logs in pod logs

### ISSUE THREAD

**Issue by captainfalcon23** [SumoLogic/sumologic-kubernetes-collection#3164]
**Describe the bug** A clear and concise description of what the bug is.

As per the title, Helm Chart Version v3.10 Logs Collector results in hundreds of "Failed to process entry" logs in pod logs. Seems to be related to AWS ELB health check logs, and open-telementrys own logs. It then seems to not know where to break each of the log entries and they get progressively  appended to each other.

**Logs** Logs which can be helpful in investigating the issue.
See attached -> 
[logs.txt](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/12166923/logs.txt)

**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.
```
helm \
                        diff upgrade \
                        --detailed-exitcode \
                        --install ${RELEASE_NAME} \
                        --namespace ${NAMESPACE} \
                        --version "${CHART_VERSION}" \
                        ${CHART}
```
**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.
```
namespaceOverride: monitoring
sumologic:
  setupEnabled: false
  cleanupEnabled: false
  accessId: XXXX
  accessKey: XXXX
  endpoint: 'https://api.au.sumologic.com/api/'
  httpProxy: 'http://proxy:8888'
  httpsProxy: 'http://proxy:8888'
  noProxy: 'kubernetes.default.svc,blah.gr7.ap-southeast-2.eks.amazonaws.com'
  clusterName: blah
  cluster:
    host: 'https://blah.gr7.ap-southeast-2.eks.amazonaws.com'
  setup:
    job:
      image:
        repository: >-
          INTERNAL_AWS_ACCT.dkr.ecr.ap-southeast-2.amazonaws.com/blah-sumologic-kubernetes-setup
        tag: 3.9.0-blah-7918
    monitors:
      enabled: false
    dashboards:
      enabled: true
  otelcolImage:
    repository: >-
      INTERNAL_AWS_ACCT.dkr.ecr.ap-southeast-2.amazonaws.com/blah-sumologic-otel-collector
    tag: 0.79.0-sumo-0-blah-7919
  events:
    enabled: true
  logs:
    enabled: true
    collector:
      otelcol:
        enabled: true
    multiline:
      enabled: true
    container:
      enabled: true
    systemd:
      enabled: true
    sourceType: http
  metrics:
    enabled: false
  traces:
    enabled: false
otelcolInstrumentation:
  enabled: true
  statefulset:
    image:
      pullPolicy: IfNotPresent
metadata:
  image:
    pullPolicy: IfNotPresent
  metrics:
    enabled: false
    logLevel: info
  logs:
    enabled: true
    logLevel: info
otelevents:
  image:
    pullPolicy: IfNotPresent
  logLevel: info
otellogs:
  config:
    merge:
      receivers:
        filelog/containers:
          include_file_name: true
          include_file_path: false
          include_file_path_resolved: true
  metrics:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  logLevel: info
    initContainers:
      changeowner:
        image:
          repository: >-
            INTERNAL_AWS_ACCT.dkr.ecr.ap-southeast-2.amazonaws.com/blah-sumologic-busybox
          tag: 1.36.0-blah-7917
          pullPolicy: IfNotPresent
telegraf-operator:
  enabled: false
falco:
  enabled: false
tailing-sidecar-operator:
  enabled: false
opentelemetry-operator:
  enabled: false
pvcCleaner:
  metrics:
    enabled: false
  logs:
    enabled: false
tracesGateway:
  enabled: false
fluentd:
  monitoring:
    input: false
    output: false
  logs:
    enabled: false
  metrics:
    enabled: false
metrics-server:
  enabled: false
fluent-bit:
  enabled: false
kube-prometheus-stack:
  enabled: false

```

**To Reproduce** Steps to reproduce the behavior.
Install the latest chart, that should be enough to see it's own logs have this issue + ELB heath checks to a container running an apache web server (at least in this sample)

**Expected behavior** A clear and concise description of what you expected to happen.
No errors in logs, or helpful guidance to actually fix this.

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`):
```
helm ls -n monitoring|grep sumo
release-3-10-0          monitoring      47              2023-07-26 10:35:33.546588152 +1000 AEST        deployed        sumologic-3.10.0                3.10.0
```
- **Kubernetes version** (e.g. `kubectl version`):
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-a5565ad", GitCommit:"23f44c7dd4e8e23856387345e7cb80bf0f93ced6", GitTreeState:"clean", BuildDate:"2023-06-15T21:19:39Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider**:
AWS
- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.
This issue goes away when I remove the config:
```
      receivers:
        filelog/containers:
          include_file_name: true
          include_file_path: false
          include_file_path_resolved: true
```

These are the changes helm would ADD when the above is uncommented:
```
          - /var/log/pods/*/*/*.log
-         include_file_name: false
-         include_file_path: true
+         include_file_name: true
+         include_file_path: false
+         include_file_path_resolved: true
```
