### ISSUE TITLE
Filtering doesn't work with JSONed logs after migrating to OTEL collector

### ISSUE THREAD

**Issue by prysmakou-sa** [SumoLogic/sumologic-kubernetes-collection#3283]
After migrating to OTEL collector our JSONed logs aren't processed by filters.

Steps to reproduce:

Add a filter (eg to wipe out emails):

```
sumologic:
  metrics:
    enabled: false
  setup:
    force: true
  traces:
    enabled: false
  logs:
    priorityClassName: ${priorityClassName}
    statefulset:
      priorityClassName: ${statefulsetPriorityClassName}
    container:
      otelcol:
        extraProcessors:
          - transform/mask-email:
              log_statements:
                - context: log
                  statements:
                    - replace_pattern(body, "([a-zA-Z0-9_.+i\\-]+@)([a-zA-Z0-9\\-]+)(\\.[a-zA-Z0-9.]+)", "xxxxxx")
```

from your cluster run:
`kubectl run -it logtest  --image=node:18-alpine --restart=Never --rm -- node -e "console.error(JSON.stringify({level:'error', message:'test', data:{ email: 'test@example.com' }}));"`

Expected result: the email is filtered out from the logs in Sumologic.
The real result: the filter is ignored.

Run a similar command for the regular/string logs (to be sure it's not an issue with the filter syntax):

`kubectl run -it logtest --image=node:18-alpine --restart=Never --rm -- node -e "console.error('email: test@example.com');"`

Some more details about our environment:
EKS 1.25
helm chart 3.15.0
