### ISSUE TITLE
Additional DaemonSets for Otellogs Not Merging Correctly

### ISSUE THREAD

**Issue by Tizull** [SumoLogic/sumologic-kubernetes-collection#3300]
**Issue**

When adding additional dameonsets for `otellogs:` to nodes that have selectors and tolerations, tolerations aren't being applied to the pod. The affinity rules and the nodeSelector get applied.

**Example**

```
otellogs:
    additionalDaemonSets:
        otellogs-foo:
           nodeSelector:
               node_role: foo
           tolerations:
              - key: node_role
                 operator: Equal
                 value: foo
                  effect: "NoSchedule"
           affinity: 
              podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                     podAffinityTerm:
                          labelSelector:
                             matchExpressions:
                             - key: node_role
                                operator: In
                                values:
                                - foo
                          topologyKey: kuberntes.io/hostname
```

**Result**

The DS for the node group is created but doesn't not deploy pods on nodes until adding the tolerations to the deployment manually.
