### ISSUE TITLE
How to add Pod ID metadata

### ISSUE THREAD

**Issue by shreyas-kb** [SumoLogic/sumologic-kubernetes-collection#3396]
I'm unsure how to send through the pod ID as metadata to Sumo. I have a `podid` field already created in Sumo, and I've tried following https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/collecting-container-logs.md#adding-custom-fields and ended up with this config:

**values.yaml**
```yaml
  logs:
    enabled: true
    metadata:
      ## Defines logs metadata enrichment provider
      provider: otelcol
    container:
      otelcol:
        extraProcessors:
          - resource/add-podid-field:
            attributes:
              - action: insert
                key: podid
                from_attribute: k8s.pod.uid
```

I also extended `k8s-tagger` as I couldn't work out why the Helm template was only using a [subset](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/7aa4d1c1afc61ac2aea13e781fa332547c8569ba/deploy/helm/sumologic/conf/logs/otelcol/config.yaml#L244-L253) of the [full data](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/7aa4d1c1afc61ac2aea13e781fa332547c8569ba/deploy/helm/sumologic/values.yaml#L1413-L1426) but I'm not sure if this is relevant.

**values.yaml**
```yaml
  logs:
    config:
      merge:
        processors:
          k8s_tagger:
            extract:
              metadata:
                - containerId
                - containerName
                - daemonSetName
                - deploymentName
                - hostName
                - namespace
                - nodeName
                - podId
                - podName
                - replicaSetName
                - serviceName
                - statefulSetName
```

Am I missing any config or do I need to be looking at some otel config?

**Comment by rjury-sumo** [comment]
seems to have been removed intentionally https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2761

**Comment by astencel-sumo** [comment]
@rjury-sumo is right, this was removed intentionally, but if it is actually used, we might bring it back in as an option.

@shreyas-kb Before we bring the field back as an option in the chart, here's a workaround to get the `pod_id` field back in Sumo for logs from Kubernetes pods:

```yaml
metadata:
  logs:
    config:
      merge:
        processors:
          k8s_tagger:
            extract:
              metadata:
                - daemonSetName
                - deploymentName
                - hostName
                - namespace
                - nodeName
                - podId
                - podName
                - serviceName
                - statefulSetName
              tags:
                podid: k8s.pod.uid
```

You were right to include `podId` in the `extract.metadata` configuration of the [Kubernetes processor](https://github.com/SumoLogic/sumologic-otel-collector/blob/v0.89.0-sumo-2/pkg/processor/k8sprocessor/README.md). This should have worked, but due to a bug in the processor, the additional entry in `extract.tags` is needed. We will fix the bug and make it easier to configure this in the chart.

Other than that, you need to make sure that the `pod_id` field is added to your list of [Fields](https://help.sumologic.com/docs/manage/fields/).

**Comment by shreyas-kb** [comment]
Hey @astencel-sumo, thanks for taking a look. I used the config you provided and saw the `pod_id` field now appeared in the Dropped Fields section, so we added it to our Fields.

However we noticed the collection wasn't working anymore, and reverting the code changes fixed the issue and we saw logs coming through again. I then removed all the entries in `extract.metadata` except for `podId` and now we're getting `pod_id` successfully in our searches, and we don't seem to have lost any fields when comparing to an environment that doesn't have this code change yet. Only issue we were able to see in the logs was:

```
2023-12-11T18:00:19.718Z        warn    sumologicexporter@v0.0.0-00010101000000-000000000000/sender.go:268      There was an issue sending data {"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "status": "
200 OK", "id": "<snip>", "code": "bad.http.header.fields", "message": "X-Sumo-Fields Warning: 2 key-value pairs are dropped as they are exceeding maximum key-value pair number limit 30."}
```

Unsure if it's directly related, but it seems to have gone away now. We're unblocked for now so cheers :)

**Comment by shreyas-kb** [comment]
Woops, I was a bit too eager. Turns out we do need that metadata to be there, but not all of it - some of it appears to be redundant so I ended up with this config:

```
metadata:
  logs:
    config:
      merge:
        processors:
          k8s_tagger:
            extract:
              metadata:
                - daemonSetName
                - deploymentName
                - hostName
                - nodeName
                - podId
                - serviceName
                - statefulSetName
              tags:
                podid: k8s.pod.uid
```

I then started seeing this error in our StatefulSet:

```
2023-12-11T23:01:48.093Z        warn    sumologicexporter@v0.0.0-00010101000000-000000000000/sender.go:268      There was an issue sending data {"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "status": "200 OK", "id": "1ZL4W-Q3SF4-TWCB1", "code": "bad.http.header.fields", "message": "X-Sumo-Fields Warning: 1 key-value pairs are dropped as they are exceeding maximum key-value pair number limit 30."}
```

I then removed `hostName` from the list as it was presenting the same information as `nodeName` but still no luck.
