### ISSUE TITLE
helm -> metrics remoteWriteProxy does not work with kube-prometheus-stack

### ISSUE THREAD

**Issue by ochabaiev-boku** [SumoLogic/sumologic-kubernetes-collection#3407]
**k8s version:** 1.24 EKS
**sumologic chart version:** 4.0.1

We are trying to upgrade our 2.x.x version to 4.0.1. Planning to keep using `kube-prometheus-stack` for metrics, so the metrics related config looks like:
```yaml
sumologic:
  # ...
  metrics:
    collector:
      otelcol:
        enabled: false
    remoteWriteProxy:
      enabled: true
# ...
metadata:
  logs:
    # ...
  ## Configure metrics pipeline.
  ## This section affects only otelcol provider.
  metrics:
    enabled: false
# ...
kube-prometheus-stack:
  enabled: true
  # ...
  prometheus:
    enabled: true
    prometheusSpec:
      scrapeInterval: 2m
      scrapeTimeout: 2m
      additionalRemoteWrite:
        - url: http://$(METADATA_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.xxx
          writeRelabelConfigs:
            - action: keep
              regex: (autodiscovered.*)
              sourceLabels:
                - __name__
  # more additionalRemoteWrites
```
When the chart is applied no `remoteWriteProxy` is created.
And as a consequence obviously prometheus failing to reach out to non-existent endpoints:
```log
ts=2023-11-20T20:28:12.316Z caller=dedupe.go:112 component=remote level=warn remote_name=af90f0 url=http://sumologic-sumologic-metadata-metrics.sumologic.svc.cluster.local:9888/prometheus.metrics.operator.rule msg="Failed to send batch, retrying" err="Post \"http://sumologic-sumologic-metadata-metrics.sumologic.svc.cluster.local:9888/prometheus.metrics.operator.rule\": dial tcp: lookup sumologic-sumologic-metadata-metrics.sumologic.svc.cluster.local on 172.20.0.10:53: no such host
```
---
I briefly checked the helm hart and found out that otel metrics is a hard requirement now taking into account [this](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/b85f04de48e76b46db13e204032351f0f73b4e12/deploy/helm/sumologic/templates/_helpers/_metrics.tpl#L58), [this](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/b85f04de48e76b46db13e204032351f0f73b4e12/deploy/helm/sumologic/templates/_helpers/_metrics.tpl#L9) and [this](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/b85f04de48e76b46db13e204032351f0f73b4e12/deploy/helm/sumologic/templates/_helpers/_metrics.tpl#L24):
```tpl
{{- $enabled := false -}}
{{- if eq (include "metrics.otelcol.enabled" .) "true" }}
{{- $enabled = true -}}
{{- end -}}
{{ $enabled }}
{{- end -}}


{{/*
Check if otelcol metrics provider is enabled
Example Usage:
{{- if eq (include "metrics.otelcol.enabled" .) "true" }}

*/}}
{{- define "metrics.otelcol.enabled" -}}
{{- $enabled := false -}}
{{- if and (eq .Values.sumologic.metrics.enabled true) (eq .Values.metadata.metrics.enabled true) -}}
{{- $enabled = true -}}
{{- end -}}
{{ $enabled }}
{{- end -}}

{{/*
Check if remote write proxy is enabled.
Example Usage:
{{- if eq (include "metrics.remoteWriteProxy.enabled" .) "true" }}

*/}}
{{- define "metrics.remoteWriteProxy.enabled" -}}
{{ and (eq (include "metrics.enabled" .) "true") (eq .Values.sumologic.metrics.remoteWriteProxy.enabled true) }}
{{- end -}}
```

So, seems like to enable `remoteWriteProxy` with `prometheus` setup the following values have to be set as true:
- `.Values.sumologic.metrics.enabled`
- `.Values.metadata.metrics.enabled` the value affecting only otelcol provider.
- `.Values.sumologic.metrics.remoteWriteProxy.enabled`
If we enable all these values otelcol metrics will also be deployed which is not desired.

**Questions:**
1) is my assumption correct? because `.Values.metadata.metrics.enabled` sounds confusing mentioning it affects only otel while with prometheus setup it's not used
2) is there any other way to setup remoteWriteProxy with prometheus that I'm missing?

**Comment by sumo-drosiek** [comment]
What do you want to use `remoteWriteProxy` for, if you are not going to use otelcol to process the metrics?

**Comment by pratik-pagade** [comment]
Hi @sumo-drosiek I have a similar doubt as posted in the issue. 
I'm upgrading from v3.8x to v4.6. But I still want to keep using prometheus (v3 default). But I also want to keep forwarding the metrics collected prometheus to sumologic(since they are used by sumo alerts that we have configured). On v3.8 it works perfectly with prometheus and as well as metrics getting pushed to sumo.

The v3 default config provided in the (How to upgrade doc) https://help.sumologic.com/docs/send-data/kubernetes/v4/how-to-upgrade/#how-to-revert-to-the-v3-defaults
shows how to use the following config to keep using prometheus instead of otelcol.
But when I use this mentioned config, the metrics are not forwarded to sumologic. But when I enable the otelcol along with the prometheus config. The prometheus also available and metrics are also forwarded to sumologic.

So my question is, do we have still have to enable otelcol along with prometheus v3 default config (to make sure the metrics is forwarded  to sumo) ?

**Comment by sumo-drosiek** [comment]
According to  the graph (https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/f4278b0f537f887927588cd6e80cf2d1057ad008/docs/README.md#metrics-collection), metrics collections consists of two layers. First layer is scraping the metrics (which may be either Prometheus or OpenTelemetry Metrics Collector) and the second is OpenTelemetry Metadata Enrichment. You can replace metrics collector with Prometheus and this is supported, but you have to have metadata layer (it used to be Fluentd before, now we use OpenTelemetry Collector)

Due to above, the following configuration should be set to true:

```
metadata:
  metrics:
    enabled: true
```

Which is different than disabling metrics collector:

```
sumologic:
  metrics:
    collector:
      otelcol:
        enabled: false
```

And this is like in documentation (https://help.sumologic.com/docs/send-data/kubernetes/v4/how-to-upgrade/#how-to-revert-to-the-v3-defaults)

This is because collector and metadata enrichment are two different services. Metadata enrichment is responsible for picking up data from Prometheus/OpenTelemetry metrics collector, perform enrichment, filtering, etc and sending them to Sumo Logic like Fluentd used to do.

**Comment by pratik-pagade** [comment]
Thanks @sumo-drosiek for the detailed explanation. thats useful to understand the flow. I did turn on the metadata -> metrics -> enabled flag explicitly but I still dont see any metrics forwarded. Is there any specific config Im missing out. 
This is output of the helm get values.
https://gist.github.com/pratik-pagade/c88ce5d4a18a71261640ef3c11a5bde2

**Comment by sumo-drosiek** [comment]
@pratik-pagade Could you share list of pods for the namespace where Sumo Logic collection has been installed?

**Comment by pratik-pagade** [comment]
List of Pods:
<img width="714" alt="Screenshot 2024-04-10 at 9 35 18 AM" src="https://github.com/SumoLogic/sumologic-kubernetes-collection/assets/87086551/9ffa2f16-b171-4f8f-8b4f-0e84231f9c87">

List of deployment,ds,sts:
<img width="1063" alt="Screenshot 2024-04-10 at 9 36 07 AM" src="https://github.com/SumoLogic/sumologic-kubernetes-collection/assets/87086551/d99817f3-c04c-467b-9c9f-b2836bb7b33d">

**Comment by sumo-drosiek** [comment]
I think you can disable Open Telemetry Operator as you don't use it:
```
opentelemetry-operator:
  enabled: false
```

All pods seems to be valid. If metrics are not ingested I would like to see logs. Could you share logs from `remote-write-proxy`, `metrics` pod and `prom-prometheus-0`? It will be enough to get logs from one pod of every kind

**Comment by pratik-pagade** [comment]
[collection-sumologic-otel-metrics-pod.json](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/14950491/collection-sumologic-otel-metrics-pod.json)
[prometheus-pod.json](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/14950492/prometheus-pod.json)
[rewrite-proxy-pod.json](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/14950493/rewrite-proxy-pod.json)

I see the following errors in rewrite-proxy logs:
```"2024/04/11 19:24:49 [error] 94#94: *338691 readv() failed (104: Connection reset by peer) while reading upstream, client: 10.19.5.22, server: , request: "POST /prometheus.metrics HTTP/1.1", upstream: "http://10.20.8.246:9888/prometheus.metrics", host: "collection-sumologic-remote-write-proxy.sumologic.svc.cluster.local:9888""```

And the following error in prometheus pod logs:
```ts=2024-04-11T19:25:44.233Z caller=dedupe.go:112 component=remote level=error remote_name=6c5207 url=http://collection-sumologic-remote-write-proxy.sumologic.svc.cluster.local:9888/prometheus.metrics msg="non-recoverable error" count=116 exemplarCount=0 err="server returned HTTP status 404 Not Found: 404 page not found"```

**Comment by sumo-drosiek** [comment]
Looking at the configuration I'm assuming that you overwritten your `remoteWrite` configuration to be e.g.: `http://$(METADATA_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888` instead of `http://$(METADATA_METRICS_SVC).$(NAMESPACE):9888`, therefore endpoints are not generated correctly (https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/20f9bf8e611e0086a41257a87f08075523bc3c60/deploy/helm/sumologic/templates/_helpers/_metrics.tpl#L30-L50)

You can fix it by adding all endpoints to `metadata.metrics.config.additionalEndpoints`

```
metadata:
  metrics:
    config:
      additionalEndpoints:
        - /prometheus.metrics.state
        - /prometheus.metrics.controller-manager
        - /prometheus.metrics.scheduler
        - /prometheus.metrics.apiserver
        - /prometheus.metrics.kubelet
        - /prometheus.metrics.container
        - /prometheus.metrics.node
        - /prometheus.metrics.operator.rule
        - /prometheus.metrics
        - /prometheus.metrics.applications.nginx-ingress
        - /prometheus.metrics.applications.nginx
        - /prometheus.metrics.applications.redis
        - /prometheus.metrics.applications.jmx
        - /prometheus.metrics.kafka
        - /prometheus.metrics.applications.mysql
        - /prometheus.metrics.applications.apache
        - /prometheus.metrics.applications.sqlserver
        - /prometheus.metrics.applications.haproxy
        - /prometheus.metrics.applications.cassandra
        - /prometheus.metrics.applications.mongodb
        - /prometheus.metrics.applications.rabbitmq
        - /prometheus.metrics.applications.tomcat
        - /prometheus.metrics.applications.varnish
        - /prometheus.metrics.applications.memcached
        - /prometheus.metrics.applications.elasticsearch
        - /prometheus.metrics.applications.activemq
        - /prometheus.metrics.puma
        - /prometheus.metrics.go
        - /prometheus.metrics.pushgateway
        - /prometheus.metrics.rabbitmq
        - /prometheus.metrics.linkerd
        - /prometheus.metrics.data_pipeline
        - /prometheus.metrics.miscellaneous
```
