### ISSUE TITLE
Allow to deploy multiple instance of SumoLogic in the same Namespace

### ISSUE THREAD

**Issue by asubramanianrl** [SumoLogic/sumologic-kubernetes-collection#3413]
We consume the SumoLogic in the EU/US region so basically, everything is an individual entity. we want to deploy the Sumologic collector of both EU/US in the same namespace.

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "sumologic-configmap" in namespace "xxx" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "sumologic-us-collector": current value is "sumologic-eu-collector"`

Value File (interchange the value of EU/US)
```
sumologicSecretName: sumologic-access-secret-eu
sumologicUrl: https://api.eu.sumologic.com/api
accessKeyName: sumologic-eu-access-key
accessIdName: sumologic-eu-access-id

sumologic:
  fullnameOverride: "sumo-col-eu"
  sumologic:
    setupEnabled: true
    envFromSecret: sumologic-access-secret-eu
    traces:
      enabled: true
      spans_per_request: 100
```

Due to static configmap,  the deploy is breaking.
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/chart-configmap.yaml

- **Collection version**: 3.8.0
