### ISSUE TITLE
Collection setup fails with api secrets from an environment variable

### ISSUE THREAD

**Issue by phillycheeze** [SumoLogic/sumologic-kubernetes-collection#352]
# Summary

When trying to install the Helm Chart via a custom values.yaml file, the setup pod script fails saying that it cannot find the `access_id` and `access_secret` keys. 

# Supplementing Info
Helm version: `v3.0.2`
Sumo helm chart version: `0.12.0`
Kubectl version: `v.17.0`
K8s version: `1.14.9`
Provider: 'EKS'

# Setup

I wiped all old sumologic namespaces and old helm version
```
kubectl delete ns sumologic
kubectl create ns sumologic
```

I created the secrets manually. Here is the output:
```
$> kubectl describe secret -n sumologic sumologic-api-secret
Name:         sumologic-api-secret
Namespace:    sumologic
Labels:
Annotations:

Type:  Opaque

Data
====
access_id:      14 bytes
access_secret:  64 bytes
```

^ btw, I've tried both *access_id* and *accessId* formats, it results in the same exact error output.

I install via the Helm chart:
`helm install collection sumologic/sumologic --namespace sumologic -f sumo_custom.yaml`

My yaml has this snippet declared:
```
sumologic:
  ## Setup

  # If enabled, a pre-install hook will create Collector and Sources in Sumo Logic
  setupEnabled: true

  # If enabled, accessId and accessKey will be sourced from Secret Name given
  envFromSecret: sumologic-api-secret

  # Sumo access ID
  #accessId: ""

  # Sumo access key
  #accessKey: ""

  # Sumo API endpoint; Leave blank for automatic endpoint discovery and redirection
  # ref: https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security
  endpoint: "https://api.us2.sumologic.com/api/v1/"
```

# Logs and Error

This is the output of the _collection-sumologic-setup_ pod:
```
kubernetes_namespace.sumologic_collection_namespace: Importing from ID "sumologic"...
kubernetes_namespace.sumologic_collection_namespace: Import prepared!
Prepared kubernetes_namespace for import
kubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic]
Error: Missing required argument
on /terraform/sumo-k8s.tf line 27, in provider "sumologic":
27: provider "sumologic" {}
The argument "access_key" is required, but no definition was found.
Error: Missing required argument
on /terraform/sumo-k8s.tf line 27, in provider "sumologic":
27: provider "sumologic" {}
The argument "access_id" is required, but no definition was found.
kubernetes_secret.sumologic_collection_secret: Importing from ID "sumologic/sumologic"...
kubernetes_secret.sumologic_collection_secret: Import prepared!
Prepared kubernetes_secret for import
kubernetes_secret.sumologic_collection_secret: Refreshing state... [id=sumologic/sumologic]
Error: Cannot import non-existent remote object
While attempting to import an existing object to
kubernetes_secret.sumologic_collection_secret, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.
Error: Missing required argument
on /terraform/sumo-k8s.tf line 27, in provider "sumologic":
27: provider "sumologic" {}
The argument "access_id" is required, but no definition was found.
Error: Missing required argument
on /terraform/sumo-k8s.tf line 27, in provider "sumologic":
27: provider "sumologic" {}
The argument "access_key" is required, but no definition was found.
provider.sumologic.access_id
Enter a value:
provider.sumologic.access_key
Enter a value:
Error: sumologic provider: access_id should be set; access_key should be set;
on <input-prompt> line 1:
(source code not available)
```
