### ISSUE TITLE
When will collector image used be updated?

### ISSUE THREAD

**Issue by chrism-teal** [SumoLogic/sumologic-kubernetes-collection#3685]
The latest version in values.yaml is 0.92.0
```
   ### Global configuration for OpenTelemetry Collector
   otelcolImage:
     repository: "public.ecr.aws/sumologic/sumologic-otel-collector"
     tag: "0.92.0-sumo-0"
```

I tried running the chart with 0.98.0-sumo-0 and the json parsing breaks as well as some noise from k8s tagger that I don't see previously. Any idea when this will get updated to work with the latest image? I have some OTTL code using functions that don't exist in 0.92.0 and I'd like to get it running
