### ISSUE TITLE
seems can not collect kubelet log  in  version 4.10.0

### ISSUE THREAD

**Issue by txjjjjj** [SumoLogic/sumologic-kubernetes-collection#3850]
## env
```
sumo 4.10.0
eks 1.30
```
## issue
values.yaml

```
  logs:
    systemd:
      enabled: true
      units:
        - kubelet.service
```
Other kubelet parameters remain default.

in generate manifest

<img width="503" alt="image" src="https://github.com/user-attachments/assets/737424ef-198d-4db3-8dac-67d4066c7ce4">

but i can not search from sumo 

```
(_sourceCategory=kubernetes/kubelet)
AND _sourceHost="my eks node name"
```

Previously, I used Fluentd for collection and could retrieve logs from kubelet. After switching to Sumo's default OTEL collection, I noticed that logs from kubelet.service are now missing.
