### ISSUE TITLE
Cannot stop `istio-proxy` container logs from being consumed

### ISSUE THREAD

**Issue by nwhobart** [SumoLogic/sumologic-kubernetes-collection#3879]
Hello. 

We're running Sumologic `collection` Helm chart `4.11.1` currently. I have never tried to exclude logs from being collected at the container level but I thought it would be as easy as a few tweaks to the helm chart. Following the example `values.yaml` file we have this in our own values file: 

```
  logs:
    enabled: true
    collector:
      otelcol:
        enabled: true
    container:
      excludeContainerRegex: "^istio-proxy$"
    metadata:
      provider: otelcol
```

The logs from `istio-proxy` containers are still coming in fast and furious. I'm unsure what I'm doing wrong and would appreciate any support.

For good measure we also set this at the `otelcolInstrumentation` level:

```
otelcolInstrumentation:
  enabled: true
  sourceMetadata:
    excludeContainerRegex: "^istio-proxy$"
```

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/values.yaml#L368-L370

**Comment by ankitmahajan-appfire** [comment]
Hey @nwhobart , I am also using the same chart version. When I have upgraded the version from 4.7.0 to 4.11.1, the first job container is launched and is failing with error below.
cp: can't create '/terraform/locals.tf': Permission denied
cp: can't create '/terraform/main.tf': Permission denied
cp: can't create '/terraform/providers.tf': Permission denied
cp: can't create '/terraform/resources.tf': Permission denied
cp: can't create '/terraform/variables.tf': Permission denied
cp: can't create '/terraform/fields.tf': Permission denied
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
{
  "quota": 400,
  "remaining": 336
}
336
jq: error (at <stdin>:0): Cannot iterate over null (null)
╷
│ Error: No Terraform configuration files
│ 
│ The directory /terraform does not contain any Terraform configuration files
│ (.tf or .tf.json). To specify a different configuration directory, use the
│ -config="..." command line option.
╵

╷
│ Error: No Terraform configuration files
│ 
│ The directory /terraform does not contain any Terraform configuration files
│ (.tf or .tf.json). To specify a different configuration directory, use the
│ -config="..." command line option.
╵

╷
│ Error: No configuration files
│ 
│ Apply requires configuration to be present. Applying without a
│ configuration would mark everything for destruction, which is normally not
│ what is desired. If you would like to destroy everything, run 'terraform
│ destroy' instead.
╵
Error during applying Terraform changes


Have you faced this error or any solution ?

**Comment by rnishtala-sumo** [comment]
Please take a look at - https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/filtering.md#drop-unnecessary-logs

```
sumologic:
  logs:
    container:
      otelcol:
        extraProcessors:
          - filter/istio_proxy:
              logs:
                log_record:
                  ## Drop logs that come istio-proxy
                  - 'resource.attributes["container"] == "istio-proxy"'
```
