### ISSUE TITLE
Sumo helm chart 4.12 fails to upgrade/install

### ISSUE THREAD

**Issue by AdamDomagalsky** [SumoLogic/sumologic-kubernetes-collection#3905]
Upgrading sumo from 4.11.1 to higher version fails as well as doing a fresh install of 4.12.*

**Logs** Logs which can be helpful in investigating the issue.
```
Error: UPGRADE FAILED: resource mapping not found for name: "collection-sumologic-metrics" namespace: "sumologic" from "": no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1beta1"
ensure CRDs are installed first
```
**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.
`helm upgrade collection helm/charts/sumologic --kube-context <cluster-name> --namespace sumologic -f helm/values/<cluster-name>/sumologic/collection.yaml --install --create-namespace
`
**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.

```
_helmctl:
    chart: sumologic
  kube-prometheus-stack:
    prometheus:
      enabled: false
  metadata:
    persistence:
      enabled: false
  metrics:
    collector:
      otelcol:
        enabled: true
    enabled: true
  opentelemetry-operator:
    enabled: true
  otelcolInstrumentation:
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
    enabled: true
  otellogs:
    daemonset:
      tolerations:
      - effect: NoSchedule
        key: exclusive
        operator: Exists
    metrics:
      enabled: true
  sumologic:
    accessId: XXX
    accessKey: YYYYY
    clusterName: cluster-name
    events:
      persistence:
        enabled: false
    logs:
      collector:
        otelcol:
          enabled: true
        sources:
          metrics:
            app1:
              name: app1
            app2:
              name: app2
      events:
        enabled: false
      kubelet:
        enabled: false
      podDisruptionBudget:
        minAvailable: 1
      statefulset:
        replicaCount: 2
      traces:
        enabled: false
    metrics:
      collector:
        otelcol:
          kubelet:
            enabled: false
          scrapeInterval: 120s
      otelcol:
        extraProcessors:
        - filter/otel-metrics:
            metrics:
              exclude:
                match_type: regexp
                metric_names:
                - go_*
                - kubeproxy_*
                - otelcol_*
                - process_*
                - workqueue_*
    setup:
      job:
        resources:
          limits:
            cpu: 1000m
            memory: 4024Mi
          requests:
            cpu: 1000m
            memory: 2000Mi
        tolerations:
        - effect: NoSchedule
          key: exclusive
          operator: Equal
          value: compute
  
```
**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`): 4.12.0 & 4.12.1
- **Kubernetes version** (e.g. `kubectl version`): 1.32
- **Cloud provider**: EKS
