### ISSUE TITLE
Metric `kube_pod_container_status_last_terminated_reason` not shipped after 4.13.0 upgrade

### ISSUE THREAD

**Issue by myedes-boku** [SumoLogic/sumologic-kubernetes-collection#3951]
**Describe the bug** 
We have noticed that the metric `kube_pod_container_status_last_terminated_reason` is now missing after the upgrade from `v4.9.0` to `v4.13.0`. The metric cannot be found neither on sumologic, nor on the prometheus instance in the cluster.
There were no changes to the helm values 

**Command used to install/upgrade Collection** 
Managed by FluxCD

**Configuration** 
Configuration used for Collection e.g. user-values.yaml for helm.
```
sumologic:
  clusterName: qa
  collectorName: qa
  endpoint: https://api.sumologic.com/api/v1/
  envFromSecret: sumo-api-credentials
  setupEnabled: true
  # Traces are now enabled by default. This disables them
  traces:
    enabled: false
  events:
    sourceType: http
    sourceCategory: qa-sumo-collection
    # Sumologic replaces "-" with "/" by default, which we do not want
    sourceCategoryReplaceDash: "-"
  logs:
    sourceType: http
    container:
      format: text
      sourceCategory: qa-sumo-collection
      sourceCategoryPrefix: ""
      sourceCategoryReplaceDash: "-"
      excludeNamespaceRegex: default
  metrics:
    sourceType: http
    collector:
      otelcol:
        enabled: false
    remoteWriteProxy:
      enabled: true
    otelcol:
      extraProcessors:
        - transform/1:
            metric_statements:
              - context: resource
                statements:
                  # Setting _sourceCategory
                  - set(attributes["_sourceCategory"], "qa-sumo-collection")
        - filter/drop_kube_metrics:
            error_mode: ignore
            metrics:
              metric:
                - IsMatch(name, "^kubernetes_feature_enabled$")
  metadata:
    metrics:
      statefuleset:
        resources:
          limits:
            cpu: 1.25
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
      config:
        additionalEndpoints:
          - /prometheus.metrics.jmx-exporter
          - /prometheus.metrics.jvm-metrics
          - /prometheus.metrics.queriedmetrics-service
        merge:
          processors:
            resource/delete_source_metadata:
              attributes:
                ## Overwriting the default config in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v3/deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml#L105-L112
                ## Do not remove _sourceCategory
                # - key: _sourceCategory
                #   action: delete
                - key: _sourceHost
                  action: delete
                - key: _sourceName
                  action: delete
  kube-prometheus-stack:
    defaultRules:
      rules:
        kubelet: false
        kubernetesSystem: false
    prometheusOperator:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 250Mi
    prometheus:
      enabled: true
      additionalPodMonitors:
        - podMetricsEndpoints:
            - path: /metrics
              port: jmx-exporter
          selector:
            matchExpressions:
              - key: app
                operator: Exists
      prometheusSpec:
        scrapeInterval: 30s
        scrapeTimeout: 30s
        walCompression: true
        resources:
          limits:
            cpu: 2000m
            memory: 10Gi
          requests:
            cpu: 500m
            memory: 4Gi
        additionalRemoteWrite:
          - url: http://$(METADATA_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.jmx-exporter
            writeRelabelConfigs:
              - action: keep
                regex: (jmx_scrape.*)
                sourceLabels:
                  - __name__
          - url: http://$(METADATA_METRICS_SVC).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.jvm-metrics
            writeRelabelConfigs:
              - action: keep
                regex: (java.*)
                sourceLabels:
                  - __name__

```

**To Reproduce** 
Upgrade the sumologic collection helm chart from v4.9.0 to v4.13.0

**Expected behavior** 
According to the release notes and changelog, there should be no changes to the metrics being shipped from the kubernetes cluster.

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`): v4.13.0
- **Kubernetes version** (e.g. `kubectl version`): Issue observed on both `1.30` and `1.32`
- **Cloud provider**: AWS EKS
- **Others**:

**Anything else do we need to know** 
The metric is shipped again after updating the `kube-prometheus-stack.kube-state-metrics.prometheus.monitor.metricRelabelings` section and adding `kube_pod_container_status_last_terminated_reason` to the [regex](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v4.13.0/deploy/helm/sumologic/values.yaml#L1144). 
This was confusing because the metric was available before the upgrade and there is no mention of any changes to the list of metrics.
