### ISSUE TITLE
values.yaml referencing thanos v0.10.0 is deprecated

### ISSUE THREAD

**Issue by emcay** [SumoLogic/sumologic-kubernetes-collection#639]
v0.17.3

When deploying, or doing a docker pull for improbable/thanos:v0.10.0 you get 

`Error response from daemon: manifest for improbable/thanos:v0.10.0 not found: manifest unknown: manifest unknown`

Also, visiting the repo suggests its deprecated, myself I have used v0.6.0 as a workaround without any issues so far.

**Comment by emcay** [comment]
I resolved this with updating the following section the values.yaml, changing "thanos" to "quay.io/thanos/thanos":

```
    prometheusSpec:
      ## Define resources requests and limits for single Pods.
      resources: {}
      # requests:
      #   memory: 400Mi
      quay.io/thanos/thanos:
```
